### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by wbbrown56** [AppTapp/Installer-Issues#163] opened 2021-03-04 20:58 UTC
**Describe the crash**
When swiping to the left to remove a tweak the app crashes when clicking on "Uninstall"

**To Reproduce**
swipe to uninstall under the "Installed" tab and tap uninstall

**Expected behavior**
Needs to be able to uninstall the tweak

**Screenshots**

**Device (please complete the following information):**
 - Device: [iPhone X 10,3]
 - OS: [iOS 14.2]
 - Installer version [5.1 beta latest]
 - Jailbreak [Unc0ver 6.0.2]

**Additional context**

**Crashlog -- REQUIRED** 
[text.txt](https://github.com/AppTapp/Installer-Issues/files/6086572/text.txt)

**Comment by vanwijkdave** [comment] 2021-04-01 21:09
Duplicate of #160 which is just solved.

**Closed as completed by vanwijkdave** 2021-04-01 21:09 UTC
Labels: crash
