### ISSUE TITLE
The operation couldn't be competed. Operation not permitted.

### ISSUE THREAD

**Issue by ZzzzZesty** [AppTapp/Installer-Issues#73] opened 2020-05-27 04:07 UTC
**Describe the issue**
Just installing a tweak and randomly this comes up. Happens every time I try to install a tweak. 

**To Reproduce**
1.install tweak 
2.see results 

**Does the issue always occur when trying to reproduce it?**
Yes

**Expected behavior**
Tweak installation 
**Screenshots**
![952D58A1-7D10-4F81-9BC3-ADE691A3FDFB](https://user-images.githubusercontent.com/63427185/82976742-e2b6a280-9fad-11ea-9930-40ed286edf6e.jpeg)

**Device (please complete the following information):**
 - Device: [iPhone 11 pro]
 - OS: [13.5]
 - Version [Latest beta sorry I'm not sure]
 - Jailbreak [uncover 5.0.1]

**Additional context**

**DO NOT FORGET TO LABEL THIS REPORT**

**Comment by AppTapp** [comment] 2020-05-30 10:15
This issue was related to the jailbreak, and should since have been fixed by the Unc0ver team. If the issue is still present on the latest version of u0 please reopen the issue.

**Closed as completed by AppTapp** 2020-05-30 10:15 UTC
