### ISSUE TITLE
[BUG] Chariz repo store login

### ISSUE THREAD

**Issue by thetechwizard17** [AppTapp/Installer-Issues#43] opened 2020-03-26 14:44 UTC
**Describe the bug**
When updating to new version of installer in the store login section Chariz repo disappears

**To Reproduce**
Steps to reproduce the behaviour:
Update to newest version 

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: 5.0.2.4
 - iOS: 13.3
 - Jailbreak unc0ver
 - Device iPhone 11 Pro Max

**Additional context**

**Comment by thetechwizard17** [comment] 2020-03-26 15:02
[Video.zip](https://github.com/AppTapp/Installer-Issues/files/4387983/Video.zip)

**Comment by AppTapp** [comment] 2020-05-15 09:12
Should be fixed in later versions. If the issue is still persistent please open new issue.

**Closed as completed by AppTapp** 2020-05-15 09:12 UTC
Labels: bug
