### ISSUE TITLE
[CRASH] When pulling the Settings Banner to far, installer crashes after closing the settings

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#190] opened 2021-07-25 08:27 UTC
**Describe the crash**
If you pull down the banner in settings, and do it like in the video, installer crashes.

**To Reproduce**
Hard to say, just do the same as shown in the video
https://youtu.be/2xJDIntCbqk

**Does this issue always occurs?**
Yes, if you do it correctly, it always occurs

**Expected behavior**
Settings should just close, instead of crashing the installer
**Video**

https://youtu.be/2xJDIntCbqk

**Device (please complete the following information):**
 - Device: iPhone 12 Mini
 - OS: 14.1
 - Installer version 5.1-87
 - Jailbreak Unc0ver 6.2.0

**Crashlog -- Cr4shed** 
https://psty.io/p?q=dfe86

**Comment by SynnyGR** [comment] 2021-11-25 21:26
Hi,

I'm not able to reproduce this issue, can you try with latest beta ? Also if the crash happen again, can you reupload a crashlog (since the previous one got erased) ?

Thanks in advance

**Comment by socksprox** [comment] 2021-11-25 21:30
Hey, unfortunately  i am not a Patreon subscriber anymore, so i don't have beta access.

**Comment by SynnyGR** [comment] 2021-11-25 23:37
We haven't been able to replicate this issue internally on different devices / iOS version.
I'll close this issue and will let you reopen it if you see it again once you'd have a chance to test a new version.

Best regards

**Closed as completed by SynnyGR** 2021-11-25 23:37 UTC
Labels: crash
