### ISSUE TITLE
[BUG] No tweak compatibility indicator

### ISSUE THREAD

**Issue by KibSquib48** [AppTapp/Installer-Issues#39] opened 2020-03-23 18:32 UTC
**Describe the bug**
There is no tweak compatibility indicator on any package

**To Reproduce**
Steps to reproduce the behaviour: look up a tweak, there’s no compatibility indicator

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
An indicator shows if the tweak is compatible

**Device (please complete the following information):**
 - Installer version: 5.0.2.3
 - iOS: 13.3
 - Jailbreak: checkra1n
 - Device: iPhone 8

**Comment by AppTapp** [comment] 2020-05-15 09:15
This is by design, but will be addressed in the upcoming 5.1 redesign.

**Closed as completed by AppTapp** 2020-05-15 09:15 UTC
Labels: bug
