### ISSUE TITLE
[BUG] Local backup is not working.

### ISSUE THREAD

**Issue by Charliefr3sh** [AppTapp/Installer-Issues#129] opened 2021-01-17 06:09 UTC
**Describe the bug**
Local backup not working 

**To Reproduce**
Steps to reproduce the behaviour:
Create backup and restore

**Does the issue always occur when trying to reproduce it?** 
Yes/No
Yes
**Expected behavior**
Backups to be created 

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC3-1] 5.1-72
 - iOS: [e.g. iOS 12.1.2] iOS and iPadOS 14.3
 - Jailbreak [e.g. Checkra1n] checkra1n 
 - Device [e.g. iPhone X] iPad 6th Gen and iPhone 8 Plus

**Additional context**

Can the devs or someone acknowledge the bug and/or respond

**Comment by vanwijkdave** [comment] 2021-02-04 10:14
When you click on "Create backup" does it show a succes message with the path of the backup? And if yes, when you go to that path, is the .txt file there?

This way we can see if the problem is the backing up part or the restoring.

**Comment by Charliefr3sh** [comment] 2021-02-09 14:28
Good day

When I click Create backup, it gives me a success message, but there’s no .txt file in the backup path. When I click on restore backup, it says there’s no backup found and I should create a new back up, and the circle continues

**Comment by SynnyGR** [comment] 2021-02-17 11:06
Hi,

This issue hasn't been reproducted on several devices and on both the sandboxed (simulator) and root builds.
Please be sure to be on the latest beta in order to use this feature as the issue have already been fixed in a previous build (-72).

Have a nice day!

Regards

**Closed as completed by SynnyGR** 2021-02-17 11:06 UTC
Labels: bug
